version: "3"
name: apps
services:

  hello:
    build:
      dockerfile: app1.Dockerfile
    ports:
      - "3000:8090"

  hello-copy:
    build:
      dockerfile: app2.Dockerfile
    ports:
      - "3001:8090"